packages:
  - packages/*
  - examples/*
  - docs

hoistWorkspacePackages: false

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - oxc-resolver
  - sharp
  - unrs-resolver

saveWorkspaceProtocol: false
