name: Setup environment
description: Setup environment with Node.js, Deno and pnpm

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Create packages build cache
      id: library-build-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/packages/dynz/dist
          ${{ github.workspace }}/packages/react-hook-form-resolver/dist
        key: library-build-cache-${{ hashFiles('packages/**/*.ts', '!packages/**/*.test.ts') }}
      
    - name: Build packages
      shell: bash
      run: pnpm run build:packages