name: Release

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:

  setup_environment:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment

  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - run: pnpm test
      
      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  library_jsr:
    name: Publish library to JSR
    needs: setup_environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Publish library
        run: npx jsr publish
        working-directory: ./packages/dynz